services:
  frontend:
    container_name: frontend
    build: ./
    restart: always
    ports:
      - "4040:443"
      # - "80:80"
    volumes:
      - ./static:/code/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/app.nginx.template:/etc/nginx/templates/app.nginx.template
      - "${EB_LOG_BASE_DIR:-./frontend/nginx}/nginx-proxy:/var/log/nginx"
      - ./ssl:/etc/ssl

  # frontend:
  #   container_name: frontend
  #   build: ./frontend
  #   restart: always
  #   ports:
  #     - "4040:443"
  #     # - "80:80"
  #   volumes:
  #     - ./static:/code/static
  #     - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./frontend/nginx/app.nginx.template:/etc/nginx/templates/app.nginx.template
  #     - "${EB_LOG_BASE_DIR:-./frontend/nginx}/nginx-proxy:/var/log/nginx"
  #     - ./frontend/ssl:/etc/ssl
